apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-app
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://github.com/1KELER1/infra_argo_code
      targetRevision: main
      path: k8s/
      name: manifests

    - repoURL: https://github.com/1KELER1/CD_k8s
      targetRevision: main
      path: app/
      name: app-code

  destination:
    server: https://kubernetes.default.svc
    namespace: lb

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
      - PrunePropagationPolicy=foreground
      - Validate=true
