apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - Namespace.yaml
  - service
  - viewer-cluster-role-binding.yaml
  - viewer-cluster-role.yaml
  - admin-role.yaml
