apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - Namespace.yaml
  - viewer-cluster-role-binding.yaml
  - viewer-cluster-role.yaml
  - admin-role.yaml
images:
  - name: fastapi
    newName: ghcr.io/1keler1/cd_k8s
    newTag: latest
    digest: sha256:dc713b24fb5de2a5082917f53d5aed28adf6e17c75e46a74df54be18e3557d66
