name: Kubernetes Lint
on:
  pull_request:
    branches: [main]
    paths: ["k8s/**"]
  push:
    branches: [main]
    paths: ["k8s/**"]

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint YAML manifests
        run: yamllint -d relaxed k8s/
